### ISSUE TITLE
Using/ignoring the value of "version" in transactions for BDB Server version 1.0.0+

### ISSUE THREAD

**Issue by ttmc** [bigchaindb/bigchaindb#1558]
[The BigchainDB transaction model](https://docs.bigchaindb.com/projects/server/en/latest/data-models/transaction-model.html) contains a top-level key-value pair:
```json
    "version": "<version number of the transaction model>",
```

What values are allowed for "version"? The schema file at `bigchaindb/bigchaindb/common/schema/transaction.yaml` contains:
```yaml
  version:
    type: string
    pattern: "^0\\."
    description: |
        BigchainDB transaction schema version.
```

What will happen if someone puts "1.0" as the value for "version"?

Is the value of the "version" used by BigchainDB Server anywhere today, or is it just ignored?

If someone puts "2.0" as the value of "version" today (or with BigchainDB Server 1.0.0), will that value be ignored, so that their transaction might be considered valid today, but in the future, it won't be considered valid, once there is an actual version 2 of the transaction schema/model?

Maybe BigchainDB Server should explicitly require that the value of "version" be "1.0" starting with BigchainDB Server version 1.0.0?
