### ISSUE TITLE
[tx gen protocol] Schema validation of unfulfilled vs fulfilled transaction

### ISSUE THREAD

**Issue by sbellem** [bigchaindb/bigchaindb#1897]
# Problem
I do not understand why the current transaction schema validation tolerates two states:

* unfulfilled aka prepared
* fulfilled

See https://github.com/bigchaindb/bigchaindb/blob/master/bigchaindb/common/schema/transaction_v1.0.yaml#L107-L111:

```yaml
      fulfillment:
        anyOf:
        - type: string
          pattern: "^[a-zA-Z0-9_-]*$"
        - "$ref": "#/definitions/condition_details"
```

The fulfillment can be either a fulfillment string or a dictionary, such as in:

```python
            'fulfillment': {
                'public_key': 'JEAkEJqLbbgDRAtMm8YAjGp759Aq2qTn9eaEHUj2XePE',
                'type': 'ed25519-sha-256'
            },
```

* The above is somewhat misleading as it is not a fulfillment, but simply two attributes that could be part of a [`Ed25519Sha256`](https://github.com/bigchaindb/cryptoconditions/blob/master/cryptoconditions/types/ed25519.py#L14) instance. 
* Furthermore it is, in some cases at least, if not, all redundant with the information that can be found in the (transaction id, output index) that the input points to.  
* Additionally it could be argued that until the fulfillment string is provided, a value of `None` is just fine and enough. See explanations at https://docs.bigchaindb.com/projects/py-driver/en/latest/handcraft.html#inputs
