### ISSUE TITLE
Impose a maximum value constraint on output_index?

### ISSUE THREAD

**Issue by ttmc** [bigchaindb/bigchaindb#1901]
The `input[i].fulfills.output_index` is the index of the output being fulfilled by input `i`. The value of `output_index` should be a small integer such as 0, 1, 2, 3, ...

Currently, the JSON Schema file for transactions (`bigchaindb/common/schema/transaction_v1.0.yaml`) includes the following snippets:
```yaml
      fulfills:
        anyOf:
        - type: 'object'
          additionalProperties: false
          required:
          - output_index
          - transaction_id
          properties:
            output_index:
              "$ref": "#/definitions/offset"
```
and
```yaml
definitions:
  offset:
    type: integer
    minimum: 0
```
In other words, transaction schema validation already ensures that `output_index` is an integer greater than or equal to zero, but it puts no upper bound (maximum allowed value) on it.

That's problematic because big integers can cause problems (which is why we changed `amount` from an integer to a string in pull request #1286 ).

### Proposal

Impose a maximum value of 511 on `output_index` (in the JSON Schema file). Maybe higher but remember, it's meant to refer to the index of a transaction output. How many outputs could a transaction have, anyway?
