### ISSUE TITLE
Kubernetes config for integration tests

### ISSUE THREAD

**Issue by kansi** [bigchaindb/bigchaindb#1990]
### Description
The integration testing #1977 spec proposes to use kubernetes for implementing network driver. So, a pod spec which defines a fully functional BDB Tendermint node is required which would be used when calling [create pod](https://github.com/kubernetes-incubator/client-python/blob/master/kubernetes/docs/CoreV1Api.md#create_namespaced_pod). The [`Node`](https://github.com/bigchaindb/bigchaindb/blob/2d6dea5b6757507d3596998f96dbd35696eeb0ad/proposals/integration-infrastructure.md#network-driver-nd) class defined in the network driver spec will use this pod spec as a blueprint to create peer nodes.

The Pod config should define and connect the following containers such that they form a fully functional node:
- Tendermint
- BigchainDB
- MongoDB

**NOTE**: The Tendermint container should allow users to specify `genesis.json` and `seeds` as command line args when running the container.

**Comment by kansi** [comment]
@shahbazn @muawiakh Following is the kind of config I am looking to use with the network driver

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: bdb-t-mdb-pod
  labels:
    app: itest-pod
spec:
  containers:
  - name: bigchaindb
    image: bigchaindb/bigchaindb:tendermint-branch
    args:
      - start
  - name: bigchaindb-mongodb
    image: bigchaindb/mongodb:3.2
  - name: tendermint-container
    image: tendermint/tendermint:develop
    command: ['sh', '-c', 'tendermint node --p2p.seeds=""']
    ports:
       - containerPort: 46656
       - containerPort: 46657
    volumeMounts:
    - mountPath: /tendermint/
      name: tendermint-config
  volumes:
  - name: tendermint-config
    hostPath:
      path: /path/to/custom/genesis.json
      type: Directory

```
