### ISSUE TITLE
bigchainDB vagrant tutorial failed provisioning

### ISSUE THREAD

**Issue by kazuakiishiguro** [bigchaindb/bigchaindb#2012]
* BigchainDB version: 1.4.0 dev
* Operating System: ubuntu/xenial64 (virtualbox, 20180122.0.0)
* Deployment Type: `vagrant`
### Description
I have tried this official bigchainDB tutorial, running with vagrant 
[https://docs.bigchaindb.com/projects/server/en/v1.3.0/appendices/run-with-vagrant.html](https://docs.bigchaindb.com/projects/server/en/v1.3.0/appendices/run-with-vagrant.html)

### What I Did
Every time I hit the command vagrant up, it came out with this error below :
```==> config-node: Configuring cache buckets...
==> config-node: Running provisioner: hosts...
==> bdb-node-01: Updating hosts on: bdb-node-01
==> config-node: Configuring cache buckets...
==> config-node: Running provisioner: shell...
    config-node: Running: inline script
    config-node: Operation Sytem: ubuntu
    config-node: Version: 16.04
    config-node: Dependencies already installed:[ ansible ]
==> config-node: Configuring cache buckets...
==> config-node: Running provisioner: shell...
    config-node: Running: inline script
    config-node: 
    config-node: PLAY [all] *********************************************************************
    config-node: 
    config-node: TASK [Gathering Facts] *********************************************************
    config-node: fatal: [bdb-node-01]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Permission denied (publickey).\r\n", "unreachable": true}
    config-node:    to retry, use: --limit @/bigchaindb/configuration/bdb-deploy.retry
    config-node: 
    config-node: PLAY RECAP *********************************************************************
    config-node: bdb-node-01                : ok=0    changed=0    unreachable=1    failed=0   
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

**Comment by muawiakh** [comment]
Can you also post the contents of `bdb-config.yml` file over here?

`/path/to/bigchaindb/pkg/pkg/configuration/vars/bdb-config.yml`

Since, you faced this issue, I have tried it on a fresh installation and no issues thus far.

**Comment by kazuakiishiguro** [comment]
I have't really changed anything as far as I know.
Here is the detail of `bdb-config.yml`
```
---
deploy_docker: false #[true, false]
docker_cluster_size: 1
upstart: "/bigchaindb/scripts/bootstrap.sh"
bdb_hosts:
  - name: "bdb-node-01"
    box:
      name: "ubuntu/xenial64"
    ram: "2048"
    vcpus: "2"
    network:
      ip: "10.20.30.40"
      type: "private_network"
```
