### ISSUE TITLE
use standard mongo URI

### ISSUE THREAD

**Issue by riderx** [bigchaindb/bigchaindb#2675]
**Describe the bug**
I cannot connect to my own mongo db.

**To Reproduce**
```
version: "3.5"

services:
  cs-mongodb:
    image: mongo:4.2
    container_name: cs-mongodb
    restart: always
    command: mongod
    environment:
      TZ: Europe/Paris
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: YGaBpWbEQw2Aghmkv4
    expose:
      - 27017
  bigchaindb:
    container_name: bigchaindb
    image: bigchaindb/bigchaindb:2.0.0
    environment:
      BIGCHAINDB_DATABASE_BACKEND: localmongodb
      BIGCHAINDB_DATABASE_HOST: cs-mongodb
      BIGCHAINDB_DATABASE_LOGIN: root
      BIGCHAINDB_DATABASE_PASSWORD: YGaBpWbEQw2Aghmkv4
      BIGCHAINDB_DATABASE_PORT: 27017
      BIGCHAINDB_SERVER_BIND: 0.0.0.0:9984
      BIGCHAINDB_WSSERVER_HOST: 0.0.0.0
      BIGCHAINDB_WSSERVER_ADVERTISED_HOST: bigchaindb
      BIGCHAINDB_TENDERMINT_HOST: tendermint
      BIGCHAINDB_TENDERMINT_PORT: 26657
  tendermint:
    container_name: tendermint
    image: tendermint/tendermint:v0.31.5
    entrypoint: ''
    ports:
      - "26656:26656"
      - "26657:26657"
    command: sh -c "tendermint init && tendermint node --consensus.create_empty_blocks=false --proxy_app=tcp://bigchaindb:26658"
    restart: always
```

**Expected behavior**
Connection can't be done, normally i use 
MONGO_URL=mongodb://root:YGaBpWbEQw2Aghmkv4@cs-mongodb:27017/bigchain?authSource=admin

**Logs or terminal output**
If applicable, add add textual content to help explain your problem.
`bigchaindb.backend.exceptions.ConnectionError: Authentication failed.`

**Additional context**
